export const WEB3_INITIALIZED = "WEB3_INITIALIZED";

export const GET_ACCOUNT_SUCCESSS = "GET_ACCOUNT_SUCCESSS";

export const PAYMENT_SUCCESSS = "PAYMENT_SUCCESSS";

export const GET_TRANSACTIONS_SUCCESSS = "GET_TRANSACTIONS_SUCCESSS";
